robots: "Panda"
env_cls_path: "baseline_env.py"

env_kwargs:
  has_renderer: false
  has_offscreen_renderer: false
  use_object_obs: true
  use_camera_obs: false
  reward_shaping: true
  control_freq: 20
  horizon: 500
  hard_reset: false

n_envs: "auto"
device: "cpu"

ppo_kwargs:
  learning_rate: 0.0003
  n_steps: 512
  batch_size: 4096
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.001
  vf_coef: 0.5
  max_grad_norm: 0.5
  target_kl: 0.02
  use_sde: true           # Turns on smooth, state-dependent exploration
  sde_sample_freq: 4      # Samples new exploration noise every 4 steps
  verbose: 1
  policy_kwargs:
    log_std_init: 0
    ortho_init: true
    activation_fn: "Tanh"
    net_arch:
      pi: [256, 256]
      vf: [256, 256]

total_timesteps: 5_000_000
save_dir: "results/baseline-forreal"
checkpoint_freq: 1_000_000
eval_freq: 50_000
n_eval_episodes: 10
early_stop: false

wandb:
  project: "robosuite"   # user fills this in
  entity: null  # optional, uses default entity if null
